apiVersion: v1
kind: Service
metadata:
  name: simple-api
  namespace: mlops-api
spec:
  selector:
    app: simple-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
